#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Resource", IsApplication=true)]

namespace Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int AmountChartButton = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int ChartsButton = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int DistributionChartButton = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int MapButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int NoteButton = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int ReminderButton = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int SaveButton = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int SpecificNeighborhoodButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int TheftChartButton = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int textView1 = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AmountChart = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Charts = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DBConnectTest = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DistributionChart = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Map = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Note = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Reminder = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SpecificNeighborhood = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TheftChart = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int AmountChart = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int ApplicationName = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int Charts = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int DistributionChart = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int Map = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Note = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int Reminder = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int Save = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int SpecificNeighborhoodChart = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int TheftChart = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
