#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Resource", IsApplication=true)]

namespace Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Deelgemeente = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int AmountChartButton = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int ChartsButton = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int DistributionChartButton = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int DistributionChartButton2 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int MapButton = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int NeighborhoodButton2 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int NoteButton = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int ReminderButton = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int SaveButton = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int SpecificNeighborhoodButton = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int bar2 = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int spinner1 = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AmountChart = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Charts = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DBConnectTest = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DistributionChart = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Map = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Neighborhood = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NodeLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Note = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Reminder = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SpecificNeighborhood = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TheftChart = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int AmountChart = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int ApplicationName = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int BeginDeel = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int Charts = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int DistributionChart = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int DistributionChart2 = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int Map = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int Neighborhoodchart = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int Note = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int Reminder = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int Save = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int SpecificNeighborhoodChart = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int TheftChart = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
